[build]
  publish = "public"
  command = "echo 'No build step needed'"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/check-interactions"
  to   = "/.netlify/functions/check-interactions"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
