[build]
  publish = "public"
  command = "cd netlify/functions && npm install"

[[redirects]]
  from = "/api/check-interactions"
  to   = "/.netlify/functions/check-interactions"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
